voting_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from user_profile import views

urlpatterns = [
    path('', views.index_page),
    path('admin/', admin.site.urls),
    path('votings/', include('votings_page.urls'), name='votings'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('registration/', views.register, name='registration'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<str:name>/', views.profile, name='profile'),
    # Шаблоны для доступа к обработчикам смены пароля.
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

votings_page/urls.py
from django.urls import path
from . import views

app_name = "votings"

urlpatterns = [
    path('', views.voting_page, name='voting_page'),
    path('<int:voting_id>/', views.detail, name='detail'),
    path('<int:voting_id>/add_comment/', views.add_comment, name='add_comment'),
    path('createvote/', views.create_vote, name='create_voting_page'),
    path('<int:voting_id>/editevote/', views.edit_vote, name='edit_vote'),
    path('<int:voting_id>/complaint/', views.complaint, name='complaint'),
    path('<int:voting_id>/showcomplaints/', views.show_complaints, name='showcomplaints'),
]

votings_page/models.py
from django.contrib.auth.models import User
from django.db import models


class Voting(models.Model):
    voting_name = models.CharField('Название голосования', max_length=100)
    voting_question = models.CharField('Вопрос голосования', max_length=255)  # Вопрос голосования
    voting_type = models.CharField('', max_length=255)
    votes_number = models.IntegerField('Число голосов', default=0)  # Общее число голосов
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # Автор голосования
    pub_date = models.DateTimeField('Дата создания')  # Дата создания голосования
    commentary_number = models.IntegerField('Кол-во комментариев', default=0)  # Кол-во комментариев под голосованием
    variants = models.CharField('', max_length=2048)
    num_of_voters = models.CharField('', max_length=2048)
    id_of_voters = models.CharField('', max_length=2048)
    complaints = models.CharField('', max_length=2048)  # Жалобы на голосование

    def __str__(self):
        return self.voting_name

    class Meta:
        verbose_name = "Голосование"
        verbose_name_plural = "Голосования"


class Comment(models.Model):
    voting = models.ForeignKey(Voting, on_delete=models.CASCADE)  # Голосование, к которому привязан комментарий
    author_name = models.ForeignKey(User, on_delete=models.CASCADE)  # Имя автора комментария
    # author_name = models.CharField('Имя автора', max_length=50)  # Имя автора комментария
    comment_text = models.CharField('Текст комментария', max_length=255)  # Текст комментария

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

votings_page/forms.py
from django import forms

class UserForm(forms.Form):
    voting_name = forms.CharField('Название голосования', max_length=100)
    voting_question = forms.CharField('Вопрос голосования', max_length=255)  # Вопрос голосования
    votes_number = forms.CharField('Число голосов', max_length=16)  # Общее число голосов
    commentary_number = forms.CharField('Кол-во комментариев', max_length=16)  # Кол-во комментариев под голосованием

votings_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Voting
from django.template import RequestContext
from django.utils import timezone


def voting_page(request):
    votings_list = Voting.objects.all()
    context = {'votings_list': votings_list}

    return render(request, "votings.html", context)  # , RequestContext(request))


def detail(request, voting_id):
    try:
        vote = Voting.objects.get(id=voting_id)
    except Exception:
        raise Http404("Голосование не найдено!")

    if request.method == 'POST':
        if 'delete vote' in request.POST:
            Voting.objects.filter(id=voting_id).delete()
            return HttpResponseRedirect("/votings")
        elif 'send' in request.POST:
            variants = vote.variants.split('@#$*')
            check = []
            if vote.voting_type == '2':
                for i in variants:
                    check.append(request.POST.get(i, "none"))
            else:
                check.append(request.POST.get("checkboxes", "none"))
            users = vote.id_of_voters.split(',')
            if str(request.user.id) not in users:
                for i in range(len(variants)):
                    for j in check:
                        if variants[i] == j:
                            if i == 0:
                                frontstr = ''
                            else:
                                frontstr = vote.num_of_voters[:((i * 5) - 0)]
                            backstr = vote.num_of_voters[((i * 5) + 1):]
                            vote.num_of_voters = \
                                frontstr + str(int(vote.num_of_voters[i * 5]) + 1) + backstr
                            if str(request.user.id) not in vote.id_of_voters.split(','):
                                vote.id_of_voters += str(request.user.id) + ','
                                vote.votes_number += 1
                            vote.save()

    latest_comments_list = vote.comment_set.order_by('-id')[:10]  # Последние 10 комментариев
    variants = vote.variants.split('@#$*')
    num_of_voters = []
    for i in range(len(variants)):
        num_of_voters.append('За вариант ' + str(i + 1)
                             + ' проголосовало: ' + vote.num_of_voters.split('@#$*')[i])

    context = {'voting': vote, 'latest_comments_list': latest_comments_list, 'variants': variants,
               'num_of_voters': num_of_voters, 'author': False}

    if request.user.id == vote.author.id:  # проверка: является ли пользователь автором
        context['author'] = True

    return render(request, "detail.html", context)  # RequestContext(request))


@login_required
def add_comment(request, voting_id):
    try:
        a = Voting.objects.get(id=voting_id)
    except:
        return Http404("Голосование не найдено!")

    a.comment_set.create(author_name=request.user, comment_text=request.POST['text'])
    # a.comment_set.create(author_name=request.POST['name'], comment_text=request.POST['text'])
    a.commentary_number = a.comment_set.count()
    a.save()

    return HttpResponseRedirect(reverse('votings:detail', args=(a.id,)))


@login_required
def create_vote(request):
    context = {}
    if request.method == 'POST':
        variants = request.POST.get("variants", "none")
        variant1 = request.POST.get("variant1", "none")
        variant2 = request.POST.get("variant2", "none")
        variants3 = request.POST.get("variant3", "none")
        type = '1'
        if variants == '':
            if variants3 != '':
                variants = variants3
                type = '2'
            elif variant1 != '' and variant2 != '':
                variants = variant1 + ',' + variant2
                type = '3'
            else:
                return render(request, "createvote.html", context)
        num_of_voters = '0@#$*'
        for i in variants:
            if i == ',':
                num_of_voters += '0@#$*'
        variants = variants.replace(', ', '@#$*')
        variants = variants.replace(',', '@#$*')

        voting = Voting(
            voting_name=request.POST.get("voting_name", "none"),
            voting_question=request.POST.get("voting_question", "none"),
            voting_type=type,
            votes_number=0,  # Общее число голосов
            author=request.user,  # Автор голосования
            pub_date=timezone.localtime(timezone.now()).strftime("%Y-%m-%d %H:%M"),  # Дата создания голосования
            commentary_number=0,
            variants=variants,
            num_of_voters=num_of_voters,
            id_of_voters='',
        )
        voting.save()
        return HttpResponseRedirect('/votings/')
    return render(request, "createvote.html", context)


@login_required
def edit_vote(request, voting_id):
    try:
        vote = Voting.objects.get(id=voting_id)
        if vote.author.id != request.user.id:  # проверка: является ли пользователь автором
            return HttpResponseRedirect('/votings/')
        context = {'voting': vote}
        if request.method == 'POST':
            variants = request.POST.get("variants", "none")
            variant1 = request.POST.get("variant1", "none")
            variant2 = request.POST.get("variant2", "none")
            variants3 = request.POST.get("variant3", "none")
            type = '1'
            if (variants == ''):
                if (variants3 != ''):
                    variants = variants3
                    type = '2'
                elif (variant1 != '' and variant2 != ''):
                    variants = variant1 + ',' + variant2
                    type = '3'
                else:
                    return HttpResponseRedirect('/votings/' + str(voting_id) + '/')
            num_of_voters = '0@#$*'
            for i in variants:
                if (i == ','):
                    num_of_voters += '0@#$*'
            variants = variants.replace(', ', '@#$*')
            variants = variants.replace(',', '@#$*')
            print(variants)
            voting = Voting(
                voting_name=request.POST.get("voting_name", "none"),
                voting_question=request.POST.get("voting_question", "none"),
                voting_type=type,
                votes_number=0,
                author=vote.author,  # Автор голосования
                pub_date=vote.pub_date,  # Дата создания голосования
                commentary_number=vote.commentary_number,
                variants=variants,
                num_of_voters=num_of_voters,
                id_of_voters='',
            )
            vote.voting_name = voting.voting_name
            vote.voting_question = voting.voting_question
            vote.votes_number = voting.votes_number
            vote.commentary_number = voting.commentary_number
            vote.variants = voting.variants
            vote.num_of_voters = voting.num_of_voters
            vote.id_of_voters = ''
            vote.voting_type = voting.voting_type
            vote.votes_number = 0
            vote.save()
            return HttpResponseRedirect('/votings/' + str(voting_id) + '/')
    except Voting.DoesNotExist:
        return Http404("Голосование не найдено!")
    return render(request, "editvote.html", context)


def complaint(request, voting_id):
    context = {}
    try:
        vote = Voting.objects.get(id=voting_id)
    except Voting.DoesNotExist:
        return Http404("Голосование не найдено!")
    if request.method == 'POST':
        complaints = request.POST.get("complaint", "none")
        if complaints != 'none' and complaints != '':
            vote.complaints += complaints + '@#$*'
            vote.save()
            return HttpResponseRedirect('/votings/' + str(voting_id) + '/')
    return render(request, "complainvote.html", context)


def show_complaints(request, voting_id):
    context = {}
    try:
        vote = Voting.objects.get(id=voting_id)
    except Voting.DoesNotExist:
        return Http404("Голосование не найдено!")
    if vote.author.id != request.user.id:  # проверка: является ли пользователь автором
        return HttpResponseRedirect('/votings/')
    complaints = vote.complaints.split('@#$*')
    for i in range(len(complaints)):
        if complaints[i] == '':
            del complaints[i]
    if not complaints:
        empty = True
    else:
        empty = False
    context = {
        'complaints': complaints,
        'empty': empty,
        'voting': vote
    }
    return render(request, "showcomplaints.html", context)

votings_page/templates/complainvote.html
{% extends "base.html" %}

{% load static %}

{% block title %}Жалоба на голосование{% endblock %}

{% block extended_css %}
    <link rel="stylesheet" href="{% static 'css/registration.css/' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
             <div class="col-md-offset-3 col-md-6">
                 <form class="form-horizontal" style="overflow-x: hidden;" method="POST">
                     {% csrf_token %}
                     <span class="heading">Жалоба на голосование</span>
                     <p style="margin-top: -10px; margin-bottom: 30px;">Пожалуйста, подробно опишите причину жалобы.<br> Мы постараемся как можно быстрее принять необходимые меры.</p>

                     <textarea name="complaint" placeholder="Причина жалобы" cols="30" rows="4" style="width: 700px;"></textarea><br>
                     <input type="submit" value="Отправить">
                 </form>
             </div>
        </div>
    </div>
{% endblock %}

votings_page/templates/createvote.html
{% extends "base.html" %}

{% load static %}

{% block title %}Создать голосование{% endblock %}

{% block extended_css %}
    <script src="{% static 'js/create_voting.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/menu.css/' %}">
    <link rel="stylesheet" href="{% static 'css/create_voting.css/' %}">
{% endblock %}

{% block content %}
        <div class="container">
            <div class="row">
                 <div class="col-md-offset-3 col-md-6">
                     <form class="form-horizontal" method="POST" style="overflow-x: hidden;" >
                         {% csrf_token %}
                         <span class="heading" style="margin-bottom: -40px;">Создать голосование</span>

                         <div style="margin-top: 70px;">
                             <input name="voting_name" type="text" required placeholder="Название голосования">
                             <br>

                             <textarea style="width: 190px;" name="voting_question" required placeholder="Вопрос голосования"></textarea>
                             <br><br><br><br>
                             <p style="text-align: left;"><b>Тип голосования:</b></p>
                             <input type="button" onclick="return openType(1);" value="Один вариант из списка">
                             <input type="button" onclick="return openType(2);" value="Несколько вариантов из списка">
                             <input type="button" onclick="return openType(3);" value="Дискретное">
                             <ul class="mydiv1">
                                 <textarea name="variants" placeholder="Варианты через запятую" cols="30" rows="4"></textarea><br>
                             </ul>
                             <ul class="mydiv2">
                                 <textarea name="variant3" placeholder="Варианты через запятую" cols="30" rows="4"></textarea><br>
                             </ul>
                             <ul class="mydiv3">
                                 <input name="variant1" type="text" placeholder="Первый вариант ответа">
                                 <input name="variant2" type="text" placeholder="Второй вариант ответа">
                             </ul>
                             <br>
                             <input type="submit" class="btn btn-success" style="background-color: #12c064; margin-top: 20px; margin-right: 50px;" value="СОЗДАТЬ">
                             {% csrf_token %}
                         </div>
                     </form>
                 </div>
            </div>
        </div>



<script>
    openType(1);
</script>

{% endblock %}

votings_page/templates/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ voting.voting_name }}{% endblock %}

{% block extended_css %}
    <link rel="stylesheet" href="{% static 'css/registration.css/' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
{% endblock %}

{% block content %}
    {% if author %}
        <form method="POST" style="margin-top: 40px; margin-left: 90px; margin-bottom: 0px;">
            {% csrf_token %}
            <div style="display: flex; flex-direction: row; justify-content: flex-start; align-items: baseline;">
                <input type="submit" value="Удалить" class="btn btn-danger" name="delete vote" style="background-color: #d9534f; font-size: 14px; text-transform: none; font-weight: normal; width: 107.38px; height: 34px; text-align: center; padding: 6px 6px 6px 6px; margin-right: 30px;">
                <input type="button" value="Редактировать" class="btn btn-warning" style="padding-left: 20px; padding-right: 20px; margin-top: 10px; margin-right: 30px;"
                onclick="location.href='{% url 'votings:edit_vote' voting.id %}'">
                <input type="button" value="Просмотреть жалобы" class="btn btn-info"
                onclick="location.href='{% url 'votings:showcomplaints' voting.id %}'">
            </div>
        </form>
    {% else %}

        <form method="POST">
             <input type="button" class="btn btn-warning" style="margin-top: 40px; margin-left: 90px;" value="Пожаловаться"
                onclick="location.href='{% url 'votings:complaint' voting.id %}'">
        </form>
    {% endif %}


    <div class="container">
        <div class="row">
             <div class="col-md-offset-3 col-md-6">
                 <form class="form-horizontal" style="overflow-x: hidden; font-family: Helvetica;" method="POST">

                     <span class="heading">{{ voting.voting_name }}</span>

                     <p style="text-align: left;"><b>&#160;Автор голосования:</b> <b><a href="/profile/{{ voting.author.username }}">{{ voting.author.username }}</a></b></p>

    <p>{{ voting.voting_question}}</p>

                     <p style="text-align: left;"><b>&#160;Проголосовало:</b> {{ voting.votes_number }} человек(-а)</p><br>

                     <p style="text-align: left; font-style: italic;"><b>&#160;Дата публикации:</b> {{ voting.pub_date }}</p>
    <br>
    <h3>Варианты ответов:</h3>
    <form method="POST">
        <div style="text-align: left; font-size: 15px; line-height: 1.55;">
        {% for c in variants %}
            {% if voting.voting_type == "2" %}
            <input type = "checkbox" style="margin-bottom: 7px;" name = "{{ c }}" value="{{ c }}"> {{ c }}

            {% else %}
            <input type = "radio" name = "checkboxes" style="margin-bottom: 7px; " value="{{ c }}"/> &#160;&#160;&#160;&#160;{{ c }}
            {% endif %}
            <br>
        {% endfor %}
        <input type="submit" style="margin-top: 20px; float: right;" name="send" value="Отправить">
        {% csrf_token %}
            </div>
    </form>

    {% if author %}
                     <div style="font-size: 15px;">
                     <h3 style="text-align: center; margin-top: -15px;">Итоги голосования:</h3>
        {% for c in num_of_voters %}
                         <b>{{ c }}</b> человек(-а)
            <br>
        {% endfor %}
                         </div>
    {% endif %}
                 </form>
             </div>
        </div>
    </div>

<h3 style="text-align: center; margin-top: 50px;"><b>Комментарии ({{ voting.commentary_number }}):</b></h3><br>

<div style="margin-left: 25%;">
    {% if latest_comments_list %}
        {% for c in latest_comments_list %}
            <strong><a href="/profile/{{ c.author_name }}">{{ c.author_name }}:</a></strong>
            <p>{{ c.comment_text }}</p>
        {% endfor %}
    {% else %}
        <p>Комментарии не найдены! Станьте первым ;)</p>
    {% endif %}
<br><br>
    <form action="{% url 'votings:add_comment' voting.id %}" method="POST">
        {% csrf_token %}
        <textarea name="text" placeholder="Текст комментария" cols="85" rows="2" width="100px" height="20px"></textarea><br><br>
        <button type="submit" style="margin-bottom: 100px; margin-top: 20px; margin-right: 500px;" class="btn btn-info">Оставить комментарий</button>
    </form>

</div>


{% endblock %}

votings_page/templates/editvote.html
{% extends "base.html" %}

{% load static %}

{% block title %}Редактировать голосования{% endblock %}

{% block extended_css %}
    <script src="{% static 'js/create_voting.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/menu.css/' %}">
    <link rel="stylesheet" href="{% static 'css/create_voting.css/' %}">
{% endblock %}

{% block content %}
    <div class="container">
            <div class="row">
                 <div class="col-md-offset-3 col-md-6">
                     <form class="form-horizontal" method="POST" style="overflow-x: hidden;" >
                         {% csrf_token %}
                         <span class="heading" style="margin-bottom: -40px;">Редактировать голосование</span>

                         <div style="margin-top: 70px;">
                             <input name="voting_name" type="text" required placeholder="Название голосования" value="{{ voting.voting_name }}">
                             <br>

                             <textarea style="width: 190px;" name="voting_question" required placeholder="Вопрос голосования">{{ voting.voting_question }}</textarea>
                             <br><br><br><br>
                             <p style="text-align: left;"><b>Тип голосования:</b></p>
                             <input type="button" onclick="return openType(1);" value="Один вариант из списка">
                             <input type="button" onclick="return openType(2);" value="Несколько вариантов из списка">
                             <input type="button" onclick="return openType(3);" value="Дискретное">
                             <ul class="mydiv1">
                                 <textarea name="variants" placeholder="Варианты через запятую" cols="30" rows="4"></textarea><br>
                             </ul>
                             <ul class="mydiv2">
                                 <textarea name="variant3" placeholder="Варианты через запятую" cols="30" rows="4"></textarea><br>
                             </ul>
                             <ul class="mydiv3">
                                 <input name="variant1" type="text" placeholder="Первый вариант ответа">
                                 <input name="variant2" type="text" placeholder="Второй вариант ответа">
                             </ul>
                             <br>
                             <input type="submit" class="btn btn-success" style="background-color: #12c064; margin-top: 20px; margin-right: 50px;" value="СОЗДАТЬ">
                             {% csrf_token %}
                         </div>
                     </form>
                 </div>
            </div>
        </div>



{% endblock %}

<script>
    openType(1);
</script>

votings_page/templates/showcomplaints.html
{% extends "base.html" %}

{% load static %}

{% block title %}Просмотр жалоб{% endblock %}

{% block extended_css %}
    <script src="{% static 'js/create_voting.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/menu.css/' %}">
    <link rel="stylesheet" href="{% static 'css/create_voting.css/' %}">
{% endblock %}

{% block content %}
    {% if not empty %}
        <div class="container">
                    <div class="row">
                         <div class="col-md-offset-3 col-md-6">
                             <form class="form-horizontal" method="POST" style="overflow-x: hidden;" >
                                 {% csrf_token %}
                                 <span class="heading" style="margin-bottom: -40px;">Жалобы на статью<br> "{{ voting.voting_name }}"</span>
        </form>
                             <div style="margin-top: 30px; font-size: 15px;">
                                 <ol>
                                 {% for c in complaints %}
                                     <li>{{ c }}</li>
        {% endfor %}
                                     </ol>
                                 </div>

                         </div>
                    </div>
                </div>
    {% else %}
        <div class="container">
            <div class="row">
                 <div class="col-md-offset-3 col-md-6">
                     <form class="form-horizontal" method="POST" style="overflow-x: hidden;" >
                         {% csrf_token %}
                         <span class="heading" style="margin-bottom: -40px;">Жалоб нет - можете спать спокойно</span>
                         <p style="margin-top: 50px;">Жалоб по вашему голосованию не обнаружено!</p>
                     </form>
                 </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

votings_page/templates/votings.html
{% extends "base.html" %}

{% load static %}

{% block title %}Голосования{% endblock %}

{% block extended_css %}
    <link href="https://fonts.googleapis.com/css?family=Raleway&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
    {% if request.user.is_authenticated %}
        <button type="button" class="btn btn-success" onclick="location.href='createvote/'" style="margin-top: 40px; margin-left: 90px; margin-bottom: -20px;">Создать голосование</button>
    {% endif %}

    {% if votings_list %}
        <div class="container" style="margin-bottom: 0;">
            <div class="row" style="margin-bottom: 0;">
                 <div class="col-md-offset-3 col-md-6" style="margin-bottom: 0;">
                     <form class="form-horizontal" style="overflow-x: hidden; margin-bottom: 0;" method="POST">
                         {% csrf_token %}
                         <span class="heading" style="margin-bottom: -40px;">Список голосований</span>
                     </form>
                 </div>
            </div>
        </div>

        {% for voting in votings_list %}
        <div style="margin-left: 90px; margin-top: 50px; margin-bottom: 10px;">
            <h2>
            <a href="{% url 'votings:detail' voting.id %}" style="text-decoration: none;">
               <b> {{ voting.voting_name }}</b>
            </a><br>
                </h2>
            <font color="black" style="font-family: 'Raleway', sans-serif;">by {{ voting.author.username }}. {{ voting.pub_date }}</font>
        </div>
        {% endfor %}

        <div style="margin-bottom: 100px;">

        </div>
    {% else %}
        <div class="container">
            <div class="row">
                 <div class="col-md-offset-3 col-md-6">
                     <form class="form-horizontal" style="overflow-x: hidden;" method="POST">
                         {% csrf_token %}
                         <span class="heading">Голосования не найдены!</span>
                         <p>Ошибка! Для вас нет доступных голосований!</p>
                     </form>
                 </div>
            </div>
        </div>
    {% endif %}
{% endblock %}