voting_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from user_profile import views

urlpatterns = [
    path('', views.index_page),
    path('admin/', admin.site.urls),
    path('votings/', include('votings_page.urls'), name='votings'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('registration/', views.register, name='registration'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/<str:name>/', views.profile, name='profile'),
    # Шаблоны для доступа к обработчикам смены пароля.
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

votings_page/urls.py
from django.urls import path
from . import views

app_name = "votings"

urlpatterns = [
    path('', views.voting_page, name='voting_page'),
    path('<int:voting_id>/', views.detail, name='detail'),
    path('<int:voting_id>/add_comment/', views.add_comment, name='add_comment'),
    path('createvote/', views.create_vote, name='create_voting_page'),
    path('<int:voting_id>/editevote/', views.edit_vote, name='edit_vote'),
    path('<int:voting_id>/complaint/', views.complaint, name='complaint'),
    path('<int:voting_id>/showcomplaints/', views.show_complaints, name='showcomplaints'),
]

user_profile/models.py
from django.db import models


# class User(models.Model):
#     login = models.CharField('Логин', max_length=255)
#     password = models.CharField('Пароль', max_length=255)
#     username = models.CharField('Username', max_length=255)
#
#     def __str__(self):
#         return self.username

user_profile/forms.py
from django import forms


class RegistrationForm(forms.Form):  # Форма регистрации новых пользователей
    username = forms.CharField(label='Username', max_length=255)
    password = forms.CharField(label='Password', widget=forms.PasswordInput, max_length=50)
    email = forms.EmailField(label='E-mail', max_length=50)

user_profile/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render

from votings_page.models import Voting
from .forms import RegistrationForm
from django.http import Http404, HttpResponseRedirect
from django.contrib.auth.hashers import make_password
#
from django.contrib import messages


#


def register(request):
    context = {}

    if request.method == "POST":
        registration_data = RegistrationForm(request.POST)

        if registration_data.is_valid():
            # Обработка данных, полученных через форму "Регистрация"
            context['username'] = registration_data.data['username']
            context['password'] = registration_data.data['password']
            context['email'] = registration_data.data['email']

            # Проверяем, нет ли пользователя с таким логином в БД
            if len(User.objects.filter(username=registration_data.data['username'])) == 0:
                context['username_error'] = False
            else:
                context['username_error'] = True
                #
                messages.error(request, "Ошибка! Пользователь с таким username уже зарегистрирован!")
                #

            if len(User.objects.filter(email=context['email'])) == 0:
                context['email_error'] = False
            else:
                context['email_error'] = True
                #
                messages.error(request, "Ошибка! Пользователь с таким e-mail уже зарегистрирован!")
                #

            if context['username_error'] is False and context['email_error'] is False:
                #
                messages.success(request, "Вы успешно зарегистрировались!")
                #

                # new_user = registration_data.save(commit=False)

                new_user = User.objects.create(username=context['username'],
                                               email=context['email'])

                # new_user = User(username=context['username'],
                #    password=context['password'],
                # email=context['email'])

                new_user.set_password(registration_data.cleaned_data['password'])

                # new_user.password = make_password(new_user.password)

                new_user.save()

        # context['form'] = RegistrationForm()
    else:
        context['username'] = ""
        context['password'] = ""
        context['form'] = RegistrationForm()
        context['username_error'] = False
        context['email_error'] = False

    return render(request, 'registration.html', context)


@login_required
def profile(request, name):
    try:
        user = User.objects.get(username=name)
    except User.DoesNotExist:
        raise Http404("Такого пользователя не существует!")
    user_votings = Voting.objects.filter(author=user)
    nums_of_votings = len(user_votings)
    nums_of_votes = 0
    votings = Voting.objects.all()
    for i in votings:
        print(i.id_of_voters.split(','))
        if str(user.id) in i.id_of_voters.split(','):
            nums_of_votes += 1
    context = {
        'user' : user,
        'nums_of_votings' : nums_of_votings,
        'nums_of_votes' : nums_of_votes,
        'votings_list' : user_votings
    }
    return render(request, 'user_profile.html', context)



def index_page(request):
    return HttpResponseRedirect("/votings")

user_profile/templates/base.html
<!DOCTYPE html>
<html lang="ru">

{% load static %}

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'images/favicon.ico/' %}" type="image/x-icon">

    {% block base_css %}
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="icon" href="{% static 'images/favicon.ico/' %}" type="image/x-icon">
        <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% endblock %}

    {% block extended_css %}
    {% endblock %}
</head>

<body>
    {% include "inc/menu.html" %}

    {% if messages %}
        <ul class="messages" >
            {% for message in messages %}
                <li class="{{ message.tags }}" style="margin-bottom: 10px;">
                    {{ message|safe }}
                    <a href="#" class="close">x</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}{% endblock %}


    {% block extended_js %}
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% endblock %}
</body>

</html>

user_profile/templates/indexpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index page</title>
</head>
<body>
    {% include "inc/menu.html" %}
</body>
</html>

user_profile/templates/registration.html
{% extends "base.html" %}

{% load static %}

{% block title %}Регистрация{% endblock %}

{% block extended_css %}
    <link rel="stylesheet" href="{% static 'css/registration.css/' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'css/base.css/' %}">
{% endblock %}

{% block content %}
    <div width="300px" height="100px" class="container" style="">
    {% if username and password and not username_error and not email_error %}
        <!--<h2 style="text-align: center; color: black; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif; */">Вы успешно зарегистрировались!</h2>
-->
        <p style="text-align: center; color: black; font-family: Helvetica,sans-serif; font-size: 20px;">
            <b>Ваш логин:</b> {{ username }}<br>
            <b>Ваш пароль:</b> {{ password }}
        </p>
    {% else %}


        <!--
        <form method="POST" style="width: 300px; margin: 0 auto;">
            {% csrf_token %}
            {{ form.username.label }} : {{ form.username }}<br><br>
            {{ form.password.label }} : {{ form.password }}<br><br>
            {{ form.email.label }} : {{ form.email }}<br><br>
            <button type="submit" class="btn btn-success btn-lg">Register</button>

        </form><-->

    </div>

    <div class="container">
        <div class="row">
             <div class="col-md-offset-3 col-md-6">
                 <form class="form-horizontal" style="overflow-x: hidden;" method="POST">
                     {% csrf_token %}
                     <span class="heading">Регистрация</span>
                     <p style="margin-top: -10px;">Пожалуйста, заполните данные формы, чтобы зарегистрироваться.</p>

                     <div class="form-group">
                         <input class="form-control" id="inputUsername" placeholder="Username" name="username">
                         <i class="fa fa-user"></i>
                     </div>

                     <div class="form-group help">
                         <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="password">
                         <i class="fa fa-lock"></i>
                         <!--<a href="ЛОЛ" class="fa fa-question-circle"></a>-->
                     </div>

                     <div class="form-group help">
                         <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email">
                         <i class="fa fa-lock"></i>
                         <!--<a href="#" class="fa fa-question-circle"></a>-->
                     </div>

                     <!--<div class="form-group">
                         <div class="main-checkbox">
                             <input type="checkbox" value="none" id="checkbox1" name="check"/>
                             <label for="checkbox1"></label>
                         </div>
                         <span class="text">Запомнить</span><-->

                         <button type="submit" class="btn btn-default" style="background-color: #12c064;">ЗАРЕГИСТРИРОВАТЬСЯ</button>

                 </form>
             </div>
        </div>
    </div>
    {% endif %}
    {% include "inc/footer.html" %}

{% endblock %}

user_profile/templates/user_profile.html
{% extends "base.html" %}

{% load static %}

{% block title %}Профиль {{ user.username }}{% endblock %}

{% block extended_css %}
    <link rel="stylesheet" href="{% static 'css/registration.css/' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
             <div class="col-md-offset-3 col-md-6">
                 <form class="form-horizontal" style="overflow-x: hidden;" method="POST">
                     {% csrf_token %}
                     <span class="heading">Учётная запись</span>

                     <p style="text-align: left; font-size: 17px; font-family: 'Open Sans', sans-serif;"><b>Username:</b> {{ user.username }}</p>

                     <p style="text-align: left; font-size: 17px; font-family: 'Open Sans', sans-serif;"><b>E-mail:</b> {{ user.email }}</p>


                     <!--{{ form.password }}-->

                     <!--<div class="form-group">
                         <input class="form-control" id="inputUsername" placeholder="Username" name="username">
                         <i class="fa fa-user"></i>
                     </div>

                     <div class="form-group help">
                         <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="password">
                         <i class="fa fa-lock"></i>
                         <a href="ЛОЛ" class="fa fa-question-circle"></a>
                     </div>

                     <div class="form-group help">
                         <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email">
                         <i class="fa fa-lock"></i>
                         <a href="#" class="fa fa-question-circle"></a>
                     </div>-->

                     <!--<div class="form-group">
                         <div class="main-checkbox">
                             <input type="checkbox" value="none" id="checkbox1" name="check"/>
                             <label for="checkbox1"></label>
                         </div>
                         <span class="text">Запомнить</span><-->

                        {% if user.username == request.user.username %}
                         <button type="button" class="btn btn-default" onclick="location.href='/password_change'" style="background-color: #12c064; float: none; margin: 0;">ИЗМЕНИТЬ ПАРОЛЬ</button>
                        {% endif %}
                 </form>
             </div>
        </div>
    </div>

   <div class="container" style="margin-bottom: 0;">
            <div class="row" style="margin-bottom: 0;">
                 <div class="col-md-offset-3 col-md-6" style="margin-bottom: 0;">
                     <form class="form-horizontal" style="overflow-x: hidden; margin-bottom: 0;" method="POST">
                         {% csrf_token %}
                         <span class="heading" style="margin-bottom: -40px;">История пользователя</span>
                     </form>
                     <br><p style="text-align: left; font-size: 17px; font-family: 'Open Sans', sans-serif;"><b>Количество созданных голосований:</b> {{ nums_of_votings }}</p>
                     <p style="text-align: left; font-size: 17px; font-family: 'Open Sans', sans-serif;"><b>Количество отданных голосов:</b> {{ nums_of_votes }}</p>
                 </div>
            </div>
   </div>

   <div class="container" style="margin-bottom: 0;">
            <div class="row" style="margin-bottom: 0;">
                 <div class="col-md-offset-3 col-md-6" style="margin-bottom: 0;">
                     <form class="form-horizontal" style="overflow-x: hidden; margin-bottom: 0;" method="POST">
                         {% csrf_token %}
                         <span class="heading" style="margin-bottom: -40px;">Голосования пользователя</span>
                     </form>
                        {% if votings_list %}
                             {% for voting in votings_list %}
                                 <div style="margin-left: 90px; margin-top: 10px; margin-bottom: 5px;">
                                     <h2>
                                         <a href="{% url 'votings:detail' voting.id %}" style="text-decoration: none;">
                                         <b> {{ voting.voting_name }}</b>
                                         </a><br>
                                     </h2>
                                     <font color="black" style="font-family: 'Raleway', sans-serif;">by {{ voting.author.username }}. {{ voting.pub_date }}</font>
                                 </div>
                             {% endfor %}
                            <div style="margin-bottom: 100px;"></div>
                        {% else %}
                            <br><p style="text-align: center; margin-bottom: 100px; font-size: 17px; font-family: 'Open Sans', sans-serif;">Этот пользователь ещё не создавал голосований!</p>
                     {% endif %}
                 </div>
            </div>
   </div>



    {% include "inc/footer.html" %}
{% endblock %}